import { Project } from "@/types/project";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "1",
    slug: "sv-road-concretisation-bandra",
    title: "S.V. Road Cement Concretisation",
    type: "Road Work",
    ward: "H West",
    location: "S.V. Road, Near Lucky Restaurant, Bandra West",
    latitude: 19.0596,
    longitude: 72.8295,
    contractorName: "RPS Infraprojects Ltd",
    contractorPhone: "+91 22 2490 1234",
    budgetSanctioned: 45.5,
    budgetSpent: 32.2,
    completionPercent: 70,
    status: "In Progress",
    startDate: "2025-11-15",
    expectedCompletionDate: "2026-05-30",
    description: "Phase 2 of road concretisation to reduce waterlogging and improve traffic flow on the main arterial S.V. Road.",
    images: ["https://images.unsplash.com/photo-1541888946425-d81bb19480c5?auto=format&fit=crop&q=80&w=800"],
    updates: [
      { date: "2026-04-01", text: "Excavation for the northbound stretch completed." },
      { date: "2026-03-10", text: "Utility shifting (water lines) finalized." }
    ]
  },
  {
    id: "2",
    slug: "andheri-subway-drain-upgrade",
    title: "Andheri Subway Micro-Tunneling",
    type: "Drain Work",
    ward: "K East",
    location: "Andheri Subway, Western Express Highway",
    latitude: 19.1136,
    longitude: 72.8697,
    contractorName: "Civic-Tech Construction",
    contractorPhone: "+91 22 2687 5544",
    budgetSanctioned: 12.8,
    budgetSpent: 14.2,
    completionPercent: 85,
    status: "Delayed",
    startDate: "2025-09-01",
    expectedCompletionDate: "2026-03-15",
    description: "Installation of high-capacity drainage pipes via micro-tunneling to prevent flooding at the subway during monsoon.",
    images: ["https://images.unsplash.com/photo-1581094288338-2314dddb7ead?auto=format&fit=crop&q=80&w=800"],
    updates: [
      { date: "2026-04-05", text: "Work halted due to unforeseen rock density issues." },
      { date: "2026-02-20", text: "Secondary drain line connected to Mogra Nullah." }
    ]
  },
  {
    id: "3",
    slug: "juhu-tara-road-repair",
    title: "Juhu Tara Road Resurfacing",
    type: "Road Work",
    ward: "K West",
    location: "Juhu Tara Road, near Juhu Hotel",
    latitude: 19.0948,
    longitude: 72.8262,
    contractorName: "J. Kumar Infra",
    contractorPhone: "+91 22 2854 9988",
    budgetSanctioned: 8.4,
    budgetSpent: 8.4,
    completionPercent: 100,
    status: "Completed",
    startDate: "2025-12-01",
    expectedCompletionDate: "2026-03-01",
    description: "Mastic asphalt resurfacing of the main beach-side road to handle heavy tourist traffic.",
    images: ["https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&q=80&w=800"],
    updates: [
      { date: "2026-03-01", text: "Project completed and opened for public use." }
    ]
  },
  {
    id: "4",
    slug: "kurla-l-ward-drain-cleaning",
    title: "Mithi River Desilting (Kurla Segment)",
    type: "Drain Work",
    ward: "L Ward",
    location: "Taximen's Colony, Kurla West",
    latitude: 19.0727,
    longitude: 72.8826,
    contractorName: "Global Waste Solutions",
    contractorPhone: "+91 22 2500 1122",
    budgetSanctioned: 22.0,
    budgetSpent: 5.5,
    completionPercent: 25,
    status: "In Progress",
    startDate: "2026-03-01",
    expectedCompletionDate: "2026-05-25",
    description: "Pre-monsoon desilting and deepening of the Mithi river stretch passing through Kurla.",
    images: ["https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&q=80&w=800"],
    updates: [
      { date: "2026-04-10", text: "First phase of floating trash removal completed." }
    ]
  },
  {
    id: "5",
    slug: "dharavi-water-upgrade",
    title: "Main 1200mm Water Line Upgrade",
    type: "Water Line Repair",
    ward: "G North",
    location: "Dharavi Main Road, near Sion Station",
    latitude: 19.0380,
    longitude: 72.8538,
    contractorName: "Skyline Infra",
    contractorPhone: "+91 22 2400 3344",
    budgetSanctioned: 18.2,
    budgetSpent: 4.1,
    completionPercent: 15,
    status: "Planned",
    startDate: "2026-04-20",
    expectedCompletionDate: "2026-12-15",
    description: "Replacement of old corroded British-era water mains with new ductile iron pipes.",
    images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800"],
    updates: []
  },
  {
    id: "6",
    slug: "marine-drive-beautification",
    title: "Marine Drive Walkway Strengthening",
    type: "Road Work",
    ward: "A Ward",
    location: "Netaji Subhash Chandra Bose Road, Marine Drive",
    latitude: 18.9431,
    longitude: 72.8230,
    contractorName: "Heritage Builders",
    contractorPhone: "+91 22 2200 7788",
    budgetSanctioned: 35.0,
    budgetSpent: 12.0,
    completionPercent: 35,
    status: "In Progress",
    startDate: "2026-01-15",
    expectedCompletionDate: "2026-10-30",
    description: "Reinforcement of the sea-facing promenade and replacement of tetrapods.",
    images: ["https://images.unsplash.com/photo-1566833912802-536968846c2f?auto=format&fit=crop&q=80&w=800"],
    updates: [
      { date: "2026-03-25", text: "New tetrapod installation started near Girgaon Chowpatty." }
    ]
  },
  {
    id: "7",
    slug: "kandivali-drain-network",
    title: "Poinsur River Channelization",
    type: "Drain Work",
    ward: "R South",
    location: "Link Road, Kandivali West",
    latitude: 19.2045,
    longitude: 72.8376,
    contractorName: "Coastal Constro",
    contractorPhone: "+91 22 2800 6655",
    budgetSanctioned: 55.0,
    budgetSpent: 48.0,
    completionPercent: 90,
    status: "In Progress",
    startDate: "2025-06-01",
    expectedCompletionDate: "2026-05-01",
    description: "Widening and retaining wall construction for the Poinsur river to mitigate suburban flooding.",
    images: ["https://images.unsplash.com/photo-1541888946425-d81bb19480c5?auto=format&fit=crop&q=80&w=800"],
    updates: [
      { date: "2026-04-02", text: "Final concreting of the left bank wall in progress." }
    ]
  },
  {
    id: "8",
    slug: "chembur-pipeline-leak",
    title: "Tansa Pipeline Leakage Repair",
    type: "Water Line Repair",
    ward: "M West",
    location: "Chembur Colony, Near Golf Club",
    latitude: 19.0622,
    longitude: 72.8974,
    contractorName: "Aqua Fix Pvt Ltd",
    contractorPhone: "+91 22 2522 4433",
    budgetSanctioned: 2.5,
    budgetSpent: 2.1,
    completionPercent: 80,
    status: "Delayed",
    startDate: "2026-02-10",
    expectedCompletionDate: "2026-04-01",
    description: "Urgent repair of a major leak in the trunk main supplying water to Central Mumbai.",
    images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=800"],
    updates: [
      { date: "2026-04-01", text: "Work delayed due to proximity to high-tension power lines." }
    ]
  },
  {
    id: "9",
    slug: "mumbai-central-drainage",
    title: "Bellasis Road Sewerage Overhaul",
    type: "Drain Work",
    ward: "E Ward",
    location: "Mumbai Central Station Perimeter",
    latitude: 18.9696,
    longitude: 72.8193,
    contractorName: "Metropolitan Infra",
    contractorPhone: "+91 22 2300 1199",
    budgetSanctioned: 28.5,
    budgetSpent: 5.0,
    completionPercent: 18,
    status: "In Progress",
    startDate: "2026-03-15",
    expectedCompletionDate: "2027-01-20",
    description: "Upgrading 50-year-old sewer lines to prevent chronic waterlogging at the station entrance.",
    images: ["https://images.unsplash.com/photo-1590247813693-5541d1c609fd?auto=format&fit=crop&q=80&w=800"],
    updates: []
  },
  {
    id: "10",
    slug: "link-road-concretisation",
    title: "New Link Road Concretisation",
    type: "Road Work",
    ward: "P South",
    location: "Link Road, Goregaon West",
    latitude: 19.1630,
    longitude: 72.8390,
    contractorName: "Pragati Constructions",
    contractorPhone: "+91 22 2877 0011",
    budgetSanctioned: 62.0,
    budgetSpent: 0,
    completionPercent: 0,
    status: "Planned",
    startDate: "2026-05-15",
    expectedCompletionDate: "2027-05-15",
    description: "Full cement concretisation of the stretch between Goregaon and Oshiwara.",
    images: ["https://images.unsplash.com/photo-1541888946425-d81bb19480c5?auto=format&fit=crop&q=80&w=800"],
    updates: []
  }
];