import { z } from "zod";

// Validates the photo analysis endpoint payload.
// Defensively ensures `imageUrl` is actually a properly formed URL string.
export const AnalyzePhotoSchema = z.object({
  imageUrl: z.string().url("Must be a valid URL string"),
});

// Logs the block hash to polygon.
export const LogOnchainSchema = z.object({
  reportId: z.string().uuid("Invalid report ID format"),
  payload: z.record(z.any()), // allows passing the rating payload blocks as standard JSON objects.
});

// Provides validation for the LLM insights parameters without dropping edge-case dynamic project variables.
// Uses .passthrough() so the API doesn't strip out specific custom columns requested by the Database model.
export const ProjectInsightsSchema = z.object({
  projectData: z.object({
    id: z.string().optional(),
    title: z.string().min(1, "Project must have a title"),
    location: z.string().optional(),
    status: z.string().optional(),
    // Allow any other generic keys generated by the Database to persist and be processed by the LLM
  }).passthrough(),
});
